### ISSUE TITLE
Refactor API resources and functions

### ISSUE THREAD

**Issue by rhoofard** [baserrato/devops-custom-provider#10]
Need to switch from maps to slices.  Every helper function currently uses the global maps we have to hold all of our resources which also include maps, all of these need to be converted to slices.  We also are using certain functions to convert maps to slices in order to be able to send them over to the provider in the correct form, these need to be removed and the functions they are used in need to be refactored to reflect this change.

**Comment by baserrato** [comment]
Finished API refactoring and works with isolated module converted maps to ref lists
