### ISSUE TITLE
Joe's ticket

### ISSUE THREAD

**Issue by snowmang1** [baserrato/devops-custom-provider#47]
# We should split this up later

### Many Benefits that came out of a meeting with Joe
- [x] custom provider install process docs
- [x] #48
- [x] we NEEDING TESTING
    - [x] build a pipeline around our testing, it wont help now, however its good practice
    - [x] pipeline can as a start just run our example tf files to check
        - [x] makefile running can be first test
    - [ ]  #44 
- [x] from install to running we need to list the steps for the provider in the README/docs

**Comment by baserrato** [comment]
@snowmang1 going through the installation process doc

**Comment by snowmang1** [comment]
we have completed this ticket/epic
