### ISSUE TITLE
link to devops provider

### ISSUE THREAD

**Issue by baserrato** [baserrato/devops-custom-provider#48]
- [x] update read me to include link for locating devops-api
- [x] include steps to find and run the make file to boot up the api

**Comment by snowmang1** [comment]
no no we need to make tickets that take subsets of that ticket and address how to accomplish them. do not just link to Joe's ticket

**Comment by snowmang1** [comment]
so more clearly what you did here is fine but this ticket needs to have its own description of how to complete it, and it needs to define completeness

**Comment by baserrato** [comment]
@snowmang1 Mainly did this issue to test the shiny issue button that pops up to the right of the checkbox. Let me know if this issue is complete enough or refactor the issue in way that is more proper

**Comment by snowmang1** [comment]
yep this looks fine to me, its just bad practice to have an empty issue even if it is linked to a task list

**Comment by baserrato** [comment]
This is included in the readme located in the api that the bootcamp links to
